name: Run Daily Report REPLACE_ME_WITH_HASHTAG Hashtag
on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 3 UTC
    
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install osmsg
          pip install tweepy
          pip install -r requirements.txt
      - name: Generate Daily Hashtag REPLACE_ME_WITH_HASHTAG Stats
        run: |
          osmsg --format csv image --tags 'building' 'highway' 'waterway' 'amenity' --name stats --all_tags --hashtags REPLACE_ME_WITH_HASHTAG --charts --summary --length highway --update --name stats/REPLACE_ME_WITH_HASHTAG/Daily/stats --force
 
      - name: add stats to git
        continue-on-error: true
        run: |
          git pull
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          base_dir=stats/REPLACE_ME_WITH_HASHTAG/Daily
          mkdir -p $base_dir
          mv $base_dir/stats_summary.md $base_dir/Readme.md
          git add -f $base_dir/*
          git commit -m "Updated Daily REPLACE_ME_WITH_HASHTAG stats"
          git push

      - name : Tweet stats
        continue-on-error: true
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run : |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --git $commit_id --tweet '#REPLACE_ME_WITH_HASHTAG' --name stats/REPLACE_ME_WITH_HASHTAG/Daily/stats