name: Run Daily Report Nepal
on:
  schedule:
    - cron: "0 6 * * *" # Run every day at 6 UTC
  # push:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install osmsg
          pip install -r requirements.txt
          pip install tweepy


      - name: Generate Daily Stats
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          osmsg --url "http://download.geofabrik.de/asia/nepal-updates" --username '${{ secrets.OSM_USERNAME }}' --password '${{ secrets.OSM_PASSWORD }}' --format image csv --timezone Nepal --last_day --tags 'building' 'highway' 'waterway' 'amenity' --name stats --read_from_metadata stats/Nepal/Daily/stats_metadata.json --all_tags --changeset  --meta --temp --force
        # run: |
        #   osmsg --url "https://planet.openstreetmap.org/replication/minute" --format image csv --timezone Nepal --tags building highway waterway amenity --name stats --all_tags --last_day --country Nepal --name stats --read_from_metadata stats/Nepal/Daily/stats_metadata.json

      - name: add stats to git
        continue-on-error: true

        run: |
          git pull 
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          cp *.csv stats/Nepal/Daily/daily_nepal_stats.csv
          cp *.png stats/Nepal/Daily/charts/top_users.png
          cp stats_metadata.json stats/Nepal/Daily/stats_metadata.json

          git add -f stats/Nepal/Daily/daily_nepal_stats.csv
          git add -f stats/Nepal/Daily/stats_metadata.json
          git add -f stats/Nepal/Daily/charts/top_users.png

          git commit -m "Updated Daily Nepal stats"
          git push

      - name: Tweet Stats
        continue-on-error: true
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --tweet_last_day --tweet_nepal --git $commit_id
          mv meta.md stats/Nepal/Daily/README.md
          mv *.png stats/Nepal/Daily/charts/
          git add -f stats/Nepal/Daily/README.md
          git add -f stats/Nepal/Daily/charts/
          git commit -m "Updated Readme Daily Nepal"
          git push
