name: Run Every2days Report SNRMPNepal Hashtag
on:
  schedule:
    - cron: "0 3 */2 * *"
  # push:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install tweepy
          python setup.py install

      - name: Generate Every2days Hashtag SNRMPNepal Stats
        run: |

          osmsg --format csv image --tags 'building' 'highway' 'waterway' 'amenity' --name stats --all_tags --hashtags SNRMPNepal --charts --summary --length highway --update --name stats/SNRMPNepal/Every2days/stats --temp --force

      - name: add stats to git
        continue-on-error: true
        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          base_dir=stats/SNRMPNepal/Every2days
          mkdir -p $base_dir
          mv $base_dir/stats_summary.md $base_dir/Readme.md
          git add -f $base_dir/*
          git commit -m "Updated Every2days SNRMPNepal stats"
          git push

      - name: Tweet stats
        continue-on-error: true
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --git $commit_id --tweet '#SNRMPNepal' --name stats/SNRMPNepal/Every2days/stats
